---
name: untitled15
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  simple_animations: ^4.0.0
  firebase_core: ^1.20.0
  firebase_auth: null
  http: ^0.13.4
  shared_preferences: 2.0.12
  fluttertoast: ^8.0.9
  cached_network_image: null
  glassmorphism_ui: null
  flutter_svg: null
  dropdown_button2: null
  intl: null
  carousel_slider: ^4.1.1
  image_picker: ^0.8.5+3
  firebase_storage:
  modal_progress_hud_nsn: ^0.3.0
  random_string:
  toast:
  rflutter_alert: ^2.0.4
  delayed_display: ^2.0.0
  flutter_staggered_animations:
  animate_do: ^3.0.2
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/

  fonts:
    - family: signatra
      fonts:
      -  asset: assets/fonts/Signatra.ttf